//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPax.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditReportResults
    {
        public int Id { get; set; }
        public int AuditId { get; set; }
        public int AuditReportId { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> Severity { get; set; }
        public string IssuesJira { get; set; }
        public string Comments { get; set; }
        public string ProblemsFound { get; set; }
    }
}
