//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace KPax.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audits
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }

        [Display(Name = "Number")]
        public int ReportNumber { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Display(Name = "Scheduled date")]
        public System.DateTime ScheduledDate { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Display(Name = "Performed date")]
        public Nullable<System.DateTime> PerformedDate { get; set; }
        public string Auditor { get; set; }
        public string Comments { get; set; }
        public Nullable<int> BaselineId { get; set; }
    
        public virtual BaselinePlan BaselinePlan { get; set; }
        public virtual Project Project { get; set; }
    }
}
