//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPax.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaselinePlanAudit
    {
        public int Id { get; set; }
        public int BaselinePlanId { get; set; }
        public string Values { get; set; }
        public bool Verified { get; set; }
    
        public virtual BaselinePlan BaselinePlan { get; set; }
    }
}
