//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPax.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDB : DbContext
    {
        public EntitiesDB()
            : base("name=EntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaselineAudit> BaselineAudit { get; set; }
        public virtual DbSet<BaselineFlow> BaselineFlow { get; set; }
        public virtual DbSet<BaselineFlowProject> BaselineFlowProject { get; set; }
        public virtual DbSet<BaselinePlan> BaselinePlan { get; set; }
        public virtual DbSet<BaselinePlanAudit> BaselinePlanAudit { get; set; }
        public virtual DbSet<GitSetup> GitSetup { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectUser> ProjectUser { get; set; }
        public virtual DbSet<TeamCitySetup> TeamCitySetup { get; set; }
        public virtual DbSet<AuditReport> AuditReport { get; set; }
        public virtual DbSet<AuditReportResults> AuditReportResults { get; set; }
        public virtual DbSet<Audits> Audits { get; set; }
    }
}
