//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPax.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamCitySetup
    {
        public int Id { get; set; }
        public string Uri { get; set; }
        public string Crendential { get; set; }
        public int IdProject { get; set; }
        public string BuildId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
